name: Reagan Ashmore
opengraph:
  appId: '1029550447130474'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
logo: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/80523df1-cd2f-41ab-b9a6-20a7dec82b89.png'
color:
  saturation: 0
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#424242'
    - '#B7B7B7'
    - '#999797'
    - '#807E7F'
  rhythmicContrast: 0.9157706
typography_spectrum: 0.40681
layout_spectrum: 0.1275816380511969
analytics:
  google: UA-78958233-1
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/fc6ab4fc-0a25-4f34-9fa1-9d87f72ad99c.png'
