typography_spectrum: 0.49073
color:
  brandColors:
    - '#FFFFFF'
    - '#424242'
    - '#B7B7B7'
    - '#999797'
    - '#807E7F'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: '1029550447130474'
layout_spectrum: 0.5005
analytics:
  google: UA-78958233-1
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/80523df1-cd2f-41ab-b9a6-20a7dec82b89.png
name: Reagan Ashmore
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fc6ab4fc-0a25-4f34-9fa1-9d87f72ad99c.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Reagan Ashmore
purpose: []
